### ISSUE TITLE
Use in production env

### ISSUE THREAD

**Issue by richardscarrott** [softmantk/perflog.js#4]
Is there a particular reason you don't recommend using this in a production environment or is it merely a case of you haven't tried it?

I'd like to instrument a particular area of our code and log the timings in production and I particularly like the way this module accumulates the timings so they can be sent in a single log at a later time.

**Comment by softmantk** [comment]
Yeah,It is just because I haven't tried much in production. One of my serverless project is using this library and found there is no performance  found issue by using this, because it is just a few line of codes and logic is pretty simple.

**Comment by richardscarrott** [comment]
Yeah I took a look through the code and looks pretty sane to me. Planning on using it in production next week.
